services:
  insight:
    container_name: insight
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - insightdb
    networks:
      - insight-network

  insightdb:
    image: postgres:latest
    container_name: insightdb
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - insightdata:/var/lib/postgresql/data
    env_file: .env
    networks:
      - insight-network

  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - insight
    networks:
      - insight-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file: .env
    networks:
      - insight-network

  whatsapp:
    build:
      context: ./whatsapp
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - insight-network

volumes:
  insightdata:

networks:
  insight-network:
    driver: bridge